import path from "node:path";
import { bootstrap } from "../bootstrap.js";
import { probe, isUsed } from "../probe.js";
import { synthesize } from "../synthesize.js";
import { emitClaude } from "../emit/claude.js";
import {
  emptyLock,
  writeLock,
  readLock,
  upsertSkill,
  type Lockfile,
  type SkillEntry,
} from "../lock.js";
import { log } from "../util/log.js";
import { sha256 } from "../util/hash.js";

export interface InitOptions {
  repoRoot: string;
  yes: boolean;
}

export async function runInit(opts: InitOptions): Promise<{ lock: Lockfile; emitted: number; pendingApproval: number }> {
  const repoRoot = path.resolve(opts.repoRoot);
  log.info(`skillfit init at ${repoRoot}`);

  const boot = await bootstrap(repoRoot);
  log.ok(`bootstrap: ${boot.candidates.length} candidate skill(s) from ${boot.source}`);

  const probeResult = await probe(repoRoot);
  log.ok(`probe: ${probeResult.usage.size} unique import root(s) detected`);

  const existing = (await readLock(path.join(repoRoot, "skillfit-lock.json"))) ?? emptyLock(boot.autoskillsVersion);
  const lock: Lockfile = {
    ...emptyLock(boot.autoskillsVersion),
    skills: existing.skills,
  };

  const dropped: { id: string; reason: string }[] = [];
  const verifiedFromAutoskills: string[] = [];

  for (const cand of boot.candidates) {
    const dep = depForSkill(cand.id);
    if (dep && !isUsed(probeResult, dep)) {
      dropped.push({ id: cand.id, reason: `0 import sites for ${dep}` });
      continue;
    }
    const placeholderBody = autoskillsPlaceholderBody(cand.id);
    const entry: SkillEntry = {
      id: cand.id,
      origin: "verified",
      source: "autoskills",
      hash: sha256(placeholderBody),
    };
    upsertSkill(lock, entry);
    verifiedFromAutoskills.push(cand.id);
  }

  const synth = await synthesize(repoRoot);
  const synthEntry: SkillEntry = {
    id: "repo-rules",
    origin: "verified",
    source: "synthesized",
    hash: synth.hash,
    inputs: synth.inputs,
    model: synth.mode === "llm" ? "anthropic" : "deterministic",
  };

  const previous = lock.skills.find((s) => s.id === "repo-rules");
  if (previous && previous.approvedHash === synth.hash) {
    synthEntry.approvedAt = previous.approvedAt;
    synthEntry.approvedHash = previous.approvedHash;
  }

  upsertSkill(lock, synthEntry);
  lock.dropped = dropped;

  const skillsToEmit = [
    ...verifiedFromAutoskills.map((id) => ({ id, body: autoskillsPlaceholderBody(id) })),
  ];

  if (synthEntry.approvedHash === synth.hash) {
    skillsToEmit.push({ id: "repo-rules", body: synth.body });
  }

  const emitted = await emitClaude(repoRoot, skillsToEmit);
  await writeLock(lock, path.join(repoRoot, "skillfit-lock.json"));

  const pendingApproval = synthEntry.approvedHash === synth.hash ? 0 : 1;

  log.ok(`emitted ${emitted.length} skill(s) to .claude/skills/`);
  if (dropped.length > 0) log.info(`dropped ${dropped.length} unused skill(s): ${dropped.map((d) => d.id).join(", ")}`);
  if (pendingApproval > 0) log.warn(`repo-rules synthesis pending approval. Run: skillfit review`);

  return { lock, emitted: emitted.length, pendingApproval };
}

function depForSkill(skillId: string): string | null {
  const map: Record<string, string> = {
    react: "react",
    nextjs: "next",
    vue: "vue",
    nuxt: "nuxt",
    svelte: "svelte",
    angular: "@angular/core",
    astro: "astro",
    tailwind: "tailwindcss",
    typescript: "typescript",
    express: "express",
    hono: "hono",
    nestjs: "@nestjs/core",
    prisma: "prisma",
    drizzle: "drizzle-orm",
    zod: "zod",
    vitest: "vitest",
    playwright: "@playwright/test",
    supabase: "@supabase/supabase-js",
    "better-auth": "better-auth",
    clerk: "@clerk/nextjs",
    stripe: "stripe",
    "react-hook-form": "react-hook-form",
    threejs: "three",
    gsap: "gsap",
    expo: "expo",
    "react-native": "react-native",
  };
  return map[skillId] ?? null;
}

function autoskillsPlaceholderBody(id: string): string {
  return `---
name: ${id}
description: Placeholder skill for ${id}. Real content will be fetched from the autoskills registry on first emit.
type: stack
origin: autoskills
---

# ${id}

This is a placeholder generated by skillfit MVP. The real skill body will be pulled from the autoskills registry once the integration boundary is wired up (see RELEASE_CHECKLIST.md).

For now, this file exists to validate the end-to-end flow: detect → emit → lock.
`;
}
